apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
  labels:
    name: portfolio-backend
    app: portfolio-backend
spec:
  type: ClusterIP
  selector:
    app: portfolio-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP