apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend-deployment
  labels:
    name: portfolio-frontend
    app: portfolio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio-frontend
      app: portfolio-frontend
  template:
    metadata:
      labels:
        name: portfolio-frontend
        app: portfolio-frontend
    spec:
      containers:
        - name: portfolio-frontend
          image: portfolio-frontend-nextjs
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: portfolio-frontend-configmap