apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
  labels:
    name: portfolio-frontend
    app: portfolio-frontend
spec:
  type: ClusterIP
  selector:
    app: portfolio-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP