apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend-deployment
  labels:
    name: portfolio-backend
    app: portfolio-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio-backend
      app: portfolio-backend
  template:
    metadata:
      labels:
        name: portfolio-backend
        app: portfolio-backend
    spec:
      containers:
        - name: portfolio-backend
          image: portfolio-backend-fastapi
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: portfolio-backend-configmap